#!/bin/bash

CMD=$1

terraform ${CMD} \
  -var 'jenkins_master_ami=ami-0f5f384dbcae8d09c' \
  -var 'jenkins_key_name=bluepipeline' \
  -var 'jenkins_vpc_id=vpc-3598af4e' \
  -var 'jenkins_master_subnet_id=subnet-5aa15906' \
  -var 'jenkins_tag_customer=skylerto' \
  -var 'jenkins_tag_project=release' \
  --auto-approve
