#!/bin/bash

exec 2>&1

echo "Starting AEM Author"

export JAVA_HOME={{pkgPathFor "core/jdk8"}}

cd {{pkg.svc_var_path}}

$JAVA_HOME/bin/java {{cfg.java.opts}} -jar {{pkgPathFor "andy-dufour/aem-base"}}/AEM_6.3_Quickstart.jar {{cfg.aem.opts}}
