#!/bin/bash

exec 2>&1

echo "Starting AEM Author"

export JAVA_HOME={{pkgPathFor "core/jdk8"}}
export 

cd {{pkg.svc_var_path}}

$JAVA_HOME/bin/java {{cfg.java.opts}} -jar AEM_6.3_Quickstart.jar {{cfg.aem.author.opts}} -p {{cfg.aem.author.port}} -nofork -v
