#!/bin/bash

exec 2>&1

echo "Starting AEM Publisher"

export JAVA_HOME={{pkgPathFor "core/jdk8"}}

cd {{pkg.svc_var_path}}

$JAVA_HOME/bin/java -Xms2048M -Xmx4096M -jar {{pkgPathFor "andy-dufour/aem-base"}}/AEM_6.3_Quickstart.jar -r publish
