#!/bin/bash

exec 2>&1

echo "Starting AEM Publisher"

export JAVA_HOME={{pkgPathFor "core/jdk8"}}

cd {{pkg.svc_var_path}}

$JAVA_HOME/bin/java {{cfg.java.opts}} -jar AEM_6.3_Quickstart.jar {{cfg.aem.publish.opts}} -p {{cfg.aem.publish.port}}
